//! Generated RVA mappings for a single executable.

// DO NOT EDIT THIS FILE DIRECTLY.

use super::RvaBundle;

/// The RVAs for this executable.
///
/// These are populated from `mapper-profile.toml` in the root of this package
/// using `tools/binary-generator`.
pub const RVAS: RvaBundle = RvaBundle {
    dluid_keyboard_device_should_block_input: 0x183be70,
    dluid_mouse_device_should_block_input: 0x183c540,
    dluid_pad_device_should_block_input: 0x183d300,
    equip_game_data_deserialize: 0x5843f0,
    equip_game_data_serialize: 0x584b60,
    global_hinstance: 0x489d5a0,
    map_item_man_grant_item: 0x7c4080,
    map_item_man_ptr: 0x4769240,
    register_task: 0xf0fa50,
};
